 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/static_pages", type: :request do
  # StaticPage. As you add validations to StaticPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StaticPage.create! valid_attributes
      get static_pages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      static_page = StaticPage.create! valid_attributes
      get static_page_url(static_page)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_static_page_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      static_page = StaticPage.create! valid_attributes
      get edit_static_page_url(static_page)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StaticPage" do
        expect {
          post static_pages_url, params: { static_page: valid_attributes }
        }.to change(StaticPage, :count).by(1)
      end

      it "redirects to the created static_page" do
        post static_pages_url, params: { static_page: valid_attributes }
        expect(response).to redirect_to(static_page_url(StaticPage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StaticPage" do
        expect {
          post static_pages_url, params: { static_page: invalid_attributes }
        }.to change(StaticPage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post static_pages_url, params: { static_page: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested static_page" do
        static_page = StaticPage.create! valid_attributes
        patch static_page_url(static_page), params: { static_page: new_attributes }
        static_page.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the static_page" do
        static_page = StaticPage.create! valid_attributes
        patch static_page_url(static_page), params: { static_page: new_attributes }
        static_page.reload
        expect(response).to redirect_to(static_page_url(static_page))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        static_page = StaticPage.create! valid_attributes
        patch static_page_url(static_page), params: { static_page: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested static_page" do
      static_page = StaticPage.create! valid_attributes
      expect {
        delete static_page_url(static_page)
      }.to change(StaticPage, :count).by(-1)
    end

    it "redirects to the static_pages list" do
      static_page = StaticPage.create! valid_attributes
      delete static_page_url(static_page)
      expect(response).to redirect_to(static_pages_url)
    end
  end
end
