 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/testpages", type: :request do
  # Testpage. As you add validations to Testpage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Testpage.create! valid_attributes
      get testpages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      testpage = Testpage.create! valid_attributes
      get testpage_url(testpage)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_testpage_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      testpage = Testpage.create! valid_attributes
      get edit_testpage_url(testpage)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Testpage" do
        expect {
          post testpages_url, params: { testpage: valid_attributes }
        }.to change(Testpage, :count).by(1)
      end

      it "redirects to the created testpage" do
        post testpages_url, params: { testpage: valid_attributes }
        expect(response).to redirect_to(testpage_url(Testpage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Testpage" do
        expect {
          post testpages_url, params: { testpage: invalid_attributes }
        }.to change(Testpage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post testpages_url, params: { testpage: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested testpage" do
        testpage = Testpage.create! valid_attributes
        patch testpage_url(testpage), params: { testpage: new_attributes }
        testpage.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the testpage" do
        testpage = Testpage.create! valid_attributes
        patch testpage_url(testpage), params: { testpage: new_attributes }
        testpage.reload
        expect(response).to redirect_to(testpage_url(testpage))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        testpage = Testpage.create! valid_attributes
        patch testpage_url(testpage), params: { testpage: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested testpage" do
      testpage = Testpage.create! valid_attributes
      expect {
        delete testpage_url(testpage)
      }.to change(Testpage, :count).by(-1)
    end

    it "redirects to the testpages list" do
      testpage = Testpage.create! valid_attributes
      delete testpage_url(testpage)
      expect(response).to redirect_to(testpages_url)
    end
  end
end
